### ISSUE TITLE
arm64-v8a

### ISSUE THREAD

**Issue by louxin2015** [saki4510t/UVCCamera#105] opened 2017-01-05 03:43 UTC
Samsung S7 can not work！The phone to find with lib/arm64-v8a , couldn't find "libusb100.so"

**Comment by saki4510t** [comment] 2017-01-19 01:49
Sorry for delay.
I assume the cause of this issue is that you mixed multiple libraries;
1. libraries that have 64 bits binaries (came from others)
2. libraries that do not have 64 bits binaries (came from this repository).

At least this repository, there are few benefit to use 64 bits binary.
64 bits binary causes following things;
* increase apk/aar size
* increase memory usage
* increate battery consumption
* become slow

So please consider to exclude 64 bits binaries from your apk.
See also WiKi page [How to exclude native binaries for specific architecture(s)](https://github.com/saki4510t/UVCCamera/wiki/How-to-exclude-native-binaries-for-specific-architecture(s))

If you still needs 64 bits binaries, for example, your other libraries have only 64 bits binary etc., it is possible to build this repository for 64 bits architectures, changing `Application.mk` like this;
```
APP_ABI := all
```
or add `arm64-v8a` / `x86_64` / `mips64` to `APP_ABI`
```
APP_ABI := armeabi armeabi-v7a arm64-v8a`
```

**Comment by saki4510t** [comment] 2017-02-18 06:11
As I wrote on [How to exclude native binaries for specific architecture(s)](https://github.com/saki4510t/UVCCamera/wiki/How-to-exclude-native-binaries-for-specific-architecture(s)), I don't want to build this repository for 64 bit architectures as default setting, will close this.

**Closed** 2017-02-18 06:12 UTC
